# Generated by Django 5.0.1 on 2024-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("contact_info", models.CharField(max_length=255)),
                ("tax_id", models.CharField(max_length=20)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
